"""initial schema

Revision ID: 35aabae635f7
Revises: 
Create Date: 2026-07-14 02:06:34.320331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35aabae635f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_models',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('experiments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('owner_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('experiment_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('problem_statement', sa.Text(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('reference_tests', sa.JSON(), nullable=True),
    sa.Column('source_dataset', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_solutions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('prompt_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('model_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('generation_latency_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], ),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_results',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('solution_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('lines_of_code', sa.Integer(), nullable=True),
    sa.Column('cyclomatic_complexity', sa.Float(), nullable=True),
    sa.Column('big_o_estimate', sa.String(), nullable=True),
    sa.Column('maintainability_index', sa.Float(), nullable=True),
    sa.Column('style_score', sa.Float(), nullable=True),
    sa.Column('pep8_violations', sa.Integer(), nullable=True),
    sa.Column('docstring_coverage', sa.Float(), nullable=True),
    sa.Column('ast_summary', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['solution_id'], ['generated_solutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('solution_id')
    )
    op.create_table('embeddings',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('solution_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('vector', sa.JSON(), nullable=False),
    sa.Column('cluster_label', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['solution_id'], ['generated_solutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('solution_id')
    )
    op.create_table('execution_results',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('solution_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('passed_tests', sa.Integer(), nullable=True),
    sa.Column('total_tests', sa.Integer(), nullable=True),
    sa.Column('pass_rate', sa.Float(), nullable=True),
    sa.Column('runtime_seconds', sa.Float(), nullable=True),
    sa.Column('memory_mb', sa.Float(), nullable=True),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['solution_id'], ['generated_solutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('solution_id')
    )
    op.create_table('similarity_scores',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('solution_a_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('solution_b_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('token_similarity', sa.Float(), nullable=True),
    sa.Column('ast_similarity', sa.Float(), nullable=True),
    sa.Column('embedding_similarity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['solution_a_id'], ['generated_solutions.id'], ),
    sa.ForeignKeyConstraint(['solution_b_id'], ['generated_solutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('similarity_scores')
    op.drop_table('execution_results')
    op.drop_table('embeddings')
    op.drop_table('analysis_results')
    op.drop_table('generated_solutions')
    op.drop_table('prompts')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('ai_models')
    # ### end Alembic commands ###
