"""add fk indexes

Revision ID: ea2a1f3bf9c8
Revises: 35aabae635f7
Create Date: 2026-07-15 02:46:44.388964

Hand-written rather than autogenerated: autogenerate against a fresh
SQLite database (the only dialect available in this environment) also
emitted spurious NUMERIC->UUID `alter_column` ops for every primary key,
an artifact of SQLite's type reflection rather than a real schema change.
Those are stripped here — this migration only does what it says: add
indexes on foreign key columns, which Postgres does not create
automatically (only primary keys and explicit UNIQUE constraints get one).
"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ea2a1f3bf9c8'
down_revision: Union[str, Sequence[str], None] = '35aabae635f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_NEW_INDEXES = [
    ("ix_experiments_owner_id", "experiments", "owner_id"),
    ("ix_prompts_experiment_id", "prompts", "experiment_id"),
    ("ix_generated_solutions_prompt_id", "generated_solutions", "prompt_id"),
    ("ix_generated_solutions_model_id", "generated_solutions", "model_id"),
    ("ix_execution_results_solution_id", "execution_results", "solution_id"),
    ("ix_analysis_results_solution_id", "analysis_results", "solution_id"),
    ("ix_embeddings_solution_id", "embeddings", "solution_id"),
    ("ix_similarity_scores_solution_a_id", "similarity_scores", "solution_a_id"),
    ("ix_similarity_scores_solution_b_id", "similarity_scores", "solution_b_id"),
]

# These three carry a UNIQUE constraint (one execution/analysis/embedding
# row per solution) — the index enforces uniqueness AND speeds up the
# join, in one index, same as models.py's Column(..., unique=True, index=True).
_UNIQUE_SOLUTION_ID_INDEXES = {
    "ix_execution_results_solution_id",
    "ix_analysis_results_solution_id",
    "ix_embeddings_solution_id",
}


def upgrade() -> None:
    for index_name, table, column in _NEW_INDEXES:
        op.create_index(index_name, table, [column], unique=index_name in _UNIQUE_SOLUTION_ID_INDEXES)


def downgrade() -> None:
    for index_name, table, _column in reversed(_NEW_INDEXES):
        op.drop_index(index_name, table_name=table)
